services:
  service_park_db:
    image: postgres:17
    container_name: service_park_db
    env_file:
      - ./src/service_park/.env
    volumes:
      - service_park_db_volume:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - metrolog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - metrolog_network
    
  # redpanda-0:
  #     image: docker.redpanda.com/redpandadata/redpanda:v26.1.6
  #     command:
  #       - redpanda
  #       - start
  #       - --mode dev-container
  #       - kafka-addr external://0.0.0.0:19092
  #       - --advertise-kafka-addr external://localhost:19092
  #     ports:
  #       - "19092:19092"
  #     volumes:
  #       - redpanda-data:/var/lib/redpanda/data

  service_park_app:
    build: ./src/service_park
    container_name: service_park_app
    env_file:
      - ./src/service_park/.env
    environment:
      POSTGRES_HOST: service_park_db
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
    networks:
      - metrolog_network
    depends_on:
      service_park_db:
        condition: service_healthy
    restart: unless-stopped

  embedding-service:
    build: ./src/search_engine/ai_model
    container_name: embedding-service
    env_file:
      - ./src/search_engine/config/config.env
    environment:
      host: 0.0.0.0
      port: 8000
      log_level: info
      max_text_length: 512
      max_batch_size: 100
      bm25_index_path: ./bm25_index.pkl
      dense_embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      sparse_model: qdrant/bm25
      late_interacction_embeding_model: answerdotai/answerai-colbert-small-v1
    ports:
      - "8000:8000"
    networks:
      - metrolog_network
    restart: unless-stopped

  search-service:
    build: ./src/search_engine/
    container_name: search-service
    env_file:
      - ./src/search_engine/config/config.env
    environment:
      - qdrant_host=qdrant
      - qdrant_port_grpc=6334
      - qdrant_port_http=6333
      - collection_name=miinstance_park
      - qdrant_distance_type=Cosine
      - qdrant_vector_size=384
      - dense_count=25
      - sparse_count=25
      - multi_count=25
      - HOST=embedding-service
      - PORT=8000
      - miinstance_host=service_park_app
      - miinstance_port=8080

    ports:
      - "8090:8090"
    networks:
      - metrolog_network
    depends_on:
      qdrant:
        condition: service_started
      embedding-service:
        condition: service_started
      # redpanda-0:
        # condition: service_started
    restart: unless-stopped

  # ========== NGINX ДЛЯ ФРОНТЕНДА ==========
  nginx:
    image: nginx:alpine
    container_name: metrolog_nginx
    ports:
      - "80:80"           # HTTP
      - "443:443"         # HTTPS (опционально, если будет SSL)
    volumes:
      # Монтируем конфиг NGINX
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Монтируем статические файлы фронтенда
      - ./src/web_site:/usr/share/nginx/html:ro
    networks:
      - metrolog_network
    depends_on:
      - service_park_app
    restart: unless-stopped

networks:
  metrolog_network:
    driver: bridge
    name: metrolog_network

volumes:
  service_park_db_volume:
  qdrant_data:
  # redpanda-data: